### ISSUE TITLE
AttributeError: module 'cv2.face' has no attribute 'createLBPHFaceRecognizer'

### ISSUE THREAD

**Issue by mrtortong** [wassgha/FaceRecognitionAPI#3]
Error
   AttributeError: module 'cv2.face' has no attribute 'createLBPHFaceRecognizer'

Please recommend.

**Comment by itslemcy** [comment]
please read the solution @wassgha provided me https://github.com/wassgha/FaceRecognitionAPI/issues/2

**Comment by wassgha** [comment]
Closing for now. Tell me if you still have the issue.
